# -*- coding: utf-8 -*-
"""geoapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17vp2_VwrWiTXAsozZ6uoV9dY-DnHOGxw
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import requests
from scipy.spatial import ConvexHull
import numpy as np

# --------------------------------------------------
# Configuração da página
# --------------------------------------------------
st.set_page_config(
    page_title="Mapa de Cidades por Regional",
    layout="wide"
)

st.title("🗺️ Mapa de Lojas por Regional e Coordenador")

# --------------------------------------------------
# Cache de dados
# --------------------------------------------------
@st.cache_data
def load_geojson():
    url = "https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/brazil-states.geojson"
    return requests.get(url, timeout=20).json()

@st.cache_data
def load_data():
    # Espera colunas: ['REGIONAL', 'COORDENADOR', 'CIDADE', 'latitude', 'longitude', 'QTD_LOJAS']
    return pd.read_csv("geodata.csv")

geojson_br = load_geojson()
df_agg = load_data()

df_agg = load_data()

# --------------------------------------------------
# Filtros (sidebar)
# --------------------------------------------------
st.sidebar.header("Filtros")

coords = sorted(df_agg['COORDENADOR'].dropna().unique().tolist())
coord_sel = st.sidebar.selectbox("Coordenador", options=["Todos"] + coords, index=0)

# --------------------------------------------------
# Funções auxiliares
# --------------------------------------------------
def filter_points(df, coord_filter):
    if coord_filter is None:
        return df.copy()
    return df[df["COORDENADOR"] == coord_filter]

def current_filter(coord_sel):
    return None if coord_sel == "Todos" else coord_sel

# --------------------------------------------------
# Aplicar filtro
# --------------------------------------------------
coord_filter = current_filter(coord_sel)
df_points = filter_points(df_agg, coord_filter)

# --------------------------------------------------
# Grupos para polígonos (somente coordenador)
# --------------------------------------------------
if coord_filter is None:
    groups_to_draw = sorted(df_agg["COORDENADOR"].dropna().unique())
else:
    groups_to_draw = [coord_filter]

# --------------------------------------------------
# Scatter (pontos das lojas)
# --------------------------------------------------
fig = px.scatter_mapbox(
    df_points,
    lat='latitude',
    lon='longitude',
    color='COORDENADOR',  # agora cor por coordenador
    size='QTD_LOJAS',     # tamanho proporcional
    hover_name='CIDADE',
    hover_data={
        'COORDENADOR': True,
        'QTD_LOJAS': True,
        'latitude': False,
        'longitude': False
    },
    height=600
)

# --------------------------------------------------
# Polígonos por coordenador
# --------------------------------------------------
def neutral_fill(alpha=0.15):
    return f"rgba(60,60,60,{alpha})"

for coord in groups_to_draw:
    df_coord = df_agg[df_agg["COORDENADOR"] == coord]

    pts = df_coord[['longitude', 'latitude']].drop_duplicates().to_numpy()

    if len(pts) < 3:
        continue

    hull = ConvexHull(pts)

    polygon_lon = pts[hull.vertices, 0].tolist() + [pts[hull.vertices, 0][0]]
    polygon_lat = pts[hull.vertices, 1].tolist() + [pts[hull.vertices, 1][0]]

    fig.add_trace(go.Scattermapbox(
        lon=polygon_lon,
        lat=polygon_lat,
        mode='lines',
        fill='toself',
        fillcolor=neutral_fill(0.15),
        line=dict(color='rgba(0,0,0,0)'),
        showlegend=False,
        hovertemplate="<b>Coordenador:</b> %{text}<extra></extra>",
        text=[str(coord)] * len(polygon_lon),
        opacity=0.95
    ))

# --------------------------------------------------
# Zoom automático
# --------------------------------------------------
center, zoom = compute_bbox_center_zoom(df_points)

fig.update_layout(
    mapbox_style="white-bg",
    mapbox_center=center,
    mapbox_zoom=zoom,
    mapbox_layers=[
        {
            "source": geojson_br,
            "type": "fill",
            "color": "#eef3f8",
            "opacity": 0.75,
            "below": "traces"
        },
        {
            "source": geojson_br,
            "type": "line",
            "color": "black",
            "line": {"width": 1.2},
            "below": "traces"
        },
    ],
    margin={"r": 0, "t": 40, "l": 0, "b": 0},
    title=f"Coordenador: {coord_sel}"
)

# --------------------------------------------------
# Render
# --------------------------------------------------
st.plotly_chart(fig, use_container_width=True)

# --------------------------------------------------
# Resumo
# --------------------------------------------------
total_lojas = int(df_points['QTD_LOJAS'].sum()) if not df_points.empty else 0

st.markdown(
    f"<p style='font-size:22px; font-weight:bold;'>"
    f"Total de lojas: {total_lojas}</p>",
    unsafe_allow_html=True
)
